### ISSUE TITLE
ValueError: too many values to unpack

### ISSUE THREAD

**Issue by redbonesmith** [redbonesmith/PEP#3]
Traceback (most recent call last):
  File "C:/Users/Oleg/PycharmProjects/PEP/denmark_parliament.py", line 109, in <module>
    pprint(_get_people(parties_info))
  File "C:/Users/Oleg/PycharmProjects/PEP/denmark_parliament.py", line 98, in _get_people
    date, place = born_string.split('in')
ValueError: too many values to unpack

**Comment by redbonesmith** [comment]
fixed
